
####  Get all Products
GET http://localhost:3000/products/


####  Get Products by Id
GET http://localhost:3000/products/1


###  Creating Products
POST http://localhost:3000/products/
Content-Type: application/json


{
  "title": "Futbolka",
  "description": "Vashe zor",
  "image": "https://www.masterclass.com/cdn-cgi/image/width=1920,quality=75,format=webp/https://images.ctfassets.net/3s5io6mnxfqz/3N5iXB8yNlqVQS3xWdIIgX/fa0d654680fbd64eb5852dbbbcf4cca4/AdobeStock_303371265.jpeg",
  "price": "1$",
  "sale": "-",
  "brend": "Samo",
  "sex": "Mujik",
  "made": "Made in china",
  "sell": "16 marta",
  "season": "Qish"
}

####  UPDATE Products
PATCH http://localhost:3000/products/1
Content-Type: application/json


{
  "name": "i5-10400f-updated"
}



####  Delete
DELETE http://localhost:3000/products/1